export const mockProducts = [
  {
    id: 1,
    name: "QR-Assembly Pro X1",
    price: 24999,
    originalPrice: 29999,
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "Manufacturing",
    inStock: true,
    description:
      "Advanced manufacturing robot with precision control for assembly line operations. Increases productivity by 300% while maintaining quality standards.",
    specifications: {
      "Payload Capacity": "50kg",
      Reach: "1.8m",
      Repeatability: "±0.1mm",
      Power: "3.5kW",
      Weight: "180kg",
    },
  },
  {
    id: 2,
    name: "QR-Warehouse Navigator",
    price: 8999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Warehouse",
    inStock: true,
    description: "Autonomous mobile robot for warehouse operations, inventory management, and material transport.",
    specifications: {
      "Load Capacity": "500kg",
      "Battery Life": "12 hours",
      Navigation: "LIDAR + AI Vision",
      Speed: "2.5 m/s",
      Connectivity: "WiFi, 5G",
    },
  },
  {
    id: 3,
    name: "QR-Office Assistant Pro",
    price: 4999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Office",
    inStock: true,
    description: "Intelligent office automation robot for reception, mail delivery, and workplace assistance tasks.",
    specifications: {
      Height: "1.4m",
      "Battery Life": "10 hours",
      Navigation: "Indoor GPS + Sensors",
      Display: '12" Interactive Screen',
      "Voice Recognition": "Multi-language",
    },
  },
  {
    id: 4,
    name: "QR-Lab Analyzer",
    price: 15999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Healthcare",
    inStock: false,
    description: "Automated laboratory analysis system for healthcare facilities and research institutions.",
    specifications: {
      "Sample Capacity": "96 samples",
      "Processing Speed": "200 tests/hour",
      Accuracy: "99.9%",
      Interface: "Touch + Voice",
      Compliance: "FDA, CE certified",
    },
  },
  {
    id: 5,
    name: "QR-Production Line Controller",
    price: 18999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Manufacturing",
    inStock: true,
    description: "Central control system for automated production lines with real-time monitoring and optimization.",
    specifications: {
      "Control Points": "32 stations",
      "Response Time": "<1ms",
      Integration: "ERP, MES, SCADA",
      Display: "Multi-monitor support",
      "Data Storage": "Cloud + Local",
    },
  },
  {
    id: 6,
    name: "QR-Inventory Drone",
    price: 3999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Warehouse",
    inStock: true,
    description: "Autonomous drone system for high-bay warehouse inventory scanning and stock verification.",
    specifications: {
      "Flight Time": "45 minutes",
      "Scan Range": "30m height",
      Camera: "4K + Thermal",
      "Barcode Reading": "1D/2D codes",
      "Weather Rating": "IP65",
    },
  },
  {
    id: 7,
    name: "QR-Meeting Room Manager",
    price: 2499,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Office",
    inStock: true,
    description: "Smart meeting room automation system with scheduling, climate control, and AV management.",
    specifications: {
      "Room Capacity": "Up to 50 people",
      Controls: "Lighting, HVAC, AV",
      Integration: "Calendar, Slack, Teams",
      Display: "Wall-mounted tablet",
      "Power Management": "Smart sensors",
    },
  },
  {
    id: 8,
    name: "QR-Surgical Assistant",
    price: 45999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Healthcare",
    inStock: true,
    description: "Precision surgical robot for minimally invasive procedures with haptic feedback and AI guidance.",
    specifications: {
      "Degrees of Freedom": "7 per arm",
      Precision: "±0.1mm",
      "Haptic Feedback": "Force + Tactile",
      "Imaging Integration": "Real-time MRI/CT",
      "Safety Systems": "Triple redundancy",
    },
  },
  {
    id: 9,
    name: "QR-Quality Inspector",
    price: 12999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Manufacturing",
    inStock: true,
    description: "AI-powered quality control system with computer vision for defect detection and measurement.",
    specifications: {
      "Inspection Speed": "1000 parts/hour",
      "Detection Accuracy": "99.95%",
      "Camera Resolution": "12MP stereo",
      "Defect Types": "50+ categories",
      Integration: "MES, ERP systems",
    },
  },
  {
    id: 10,
    name: "QR-Pharmacy Dispenser",
    price: 8999,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Healthcare",
    inStock: true,
    description: "Automated medication dispensing system for hospitals and pharmacies with inventory tracking.",
    specifications: {
      "Medication Capacity": "2000+ SKUs",
      "Dispensing Speed": "120 doses/minute",
      Accuracy: "99.99%",
      Security: "Biometric + PIN",
      Compliance: "USP 797, HIPAA",
    },
  },
]
